[pypidatabot]
version = "v0.1.0" # Don't change this, it might break something

    [pypidatabot.endpoints]
    pypi-simple-index = "https://pypi.org/simple" # # Don't change this unless you know what you are doing

    [pypidatabot.redis]
    host = ""
    port = 6379
    db = 0
